### ISSUE TITLE
Issue setting up the app

### ISSUE THREAD

**Issue by Sicily-F** [69690/Flask-Webapp#3]
Hi there,

This seems like a very interesting app which I was hoping to use, however I am having issue with the set up.

I cloned the repo, then I installed the requirements text and then I changed by directory to Flask-Webapp/webapp because the flask run command didn't work when I tried just in the Flask-Webapp directory.

However, then, I received this error code, and I have included the full traceback here:

 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
d:\anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
d:\anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
d:\anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
d:\anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
d:\anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
d:\anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\Sicily\Flask-Webapp\webapp\modelRunner
C:\Users\Sicily\Flask-Webapp\webapp\static\uploads\output
C:\Users\Sicily\Flask-Webapp\webapp\static\input
C:\Users\Sicily\Flask-Webapp\webapp\static
Traceback (most recent call last):
  File "d:\anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "d:\anaconda\lib\site-packages\flask\cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "d:\anaconda\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "d:\anaconda\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\anaconda\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\anaconda\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\anaconda\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\anaconda\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "d:\anaconda\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\anaconda\lib\site-packages\flask\cli.py", line 848, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "d:\anaconda\lib\site-packages\flask\cli.py", line 305, in __init__
    self._load_unlocked()
  File "d:\anaconda\lib\site-packages\flask\cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "d:\anaconda\lib\site-packages\flask\cli.py", line 392, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "d:\anaconda\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "C:\Users\Sicily\Flask-Webapp\webapp\__init__.py", line 5, in <module>
    from webapp import views
  File "C:\Users\Sicily\Flask-Webapp\webapp\views.py", line 9, in <module>
    import webapp.modelRunner.runner
  File "C:\Users\Sicily\Flask-Webapp\webapp\modelRunner\runner.py", line 32, in <module>
    loaded_model = model_from_json(loaded_model_json, custom_objects={'PConv2D':PConv2D})
  File "d:\anaconda\lib\site-packages\tensorflow\python\keras\engine\saving.py", line 365, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "d:\anaconda\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 74, in deserialize
    printable_module_name='layer')
  File "d:\anaconda\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 192, in deserialize_keras_object
    list(custom_objects.items())))
  File "d:\anaconda\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1263, in from_config
    process_layer(layer_data)
  File "d:\anaconda\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1249, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "d:\anaconda\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 74, in deserialize
    printable_module_name='layer')
  File "d:\anaconda\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 194, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "d:\anaconda\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 402, in from_config
    return cls(**config)
  File "d:\anaconda\lib\site-packages\tensorflow\python\keras\engine\input_layer.py", line 69, in __init__
    raise ValueError('Unrecognized keyword arguments:', kwargs.keys())
ValueError: ('Unrecognized keyword arguments:', dict_keys(['ragged']))

**Comment by bharat-ahuja** [comment]
Hi there, greetings! Please run the following commands in order and try again:-
$ export FLASK_ENV=development
$ flask run

**Comment by Sicily-F** [comment]
Hi there,

So I managed to get given a link, but it says there is no application: 

![image](https://user-images.githubusercontent.com/68450039/104936551-9688fa00-59a4-11eb-87e2-adb2dc99f883.png)

**Comment by bharat-ahuja** [comment]
Hi there, I can see that you're using the base environment. Once you've pip installed the requirements after creating a venv, activate the venv (Steps are given below):-
Step 1. Change directory to root directory -> Flask-Webapp/ 
Step 2. use the following code
$ python3 -m venv env
$ source env/bin/activate 
$ pip install -r requirements.txt

Make sure you're in the root directory Flask-Webapp/
Use the following command (you've already set it to the development server in the previous step):- 
$ export FLASK_APP=run.py
$ flask run

Thanks

**Comment by Sicily-F** [comment]
Hi there - it's still not working - same error codes as before - has it been tested on Windows systems?
